### ISSUE TITLE
Fix collision between ids of different models.

### ISSUE THREAD

**Issue by orballo** [wp-pwa/wp-org-connection#5]
Media, Author and Taxonomy ids can collide between them. Find a way to avoid this behavior.

**Comment by luisherranz** [comment]
Where do they collide? They should be different models/entities in mst.

**Comment by orballo** [comment]
When a custom list is created, and I try to get the `entities`, mst doesn't know which one to return, because categories and authors would share the same id. Also happens with tags and media. So mst doesn't know if it should return a `Taxonomy` or an `Author`.

**Comment by luisherranz** [comment]
Solved via #13.
